### ISSUE TITLE
<AP> RC500S Mirror Image Function

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#4]
Is it possible to include it? Received some inquiries for parking.

**Comment by dod-pm1** [comment]
We have thought about this, but decide NOT to include.
reason being, you SHOULD NOT hold your phone while driving.
Since the RC does not have LCD display, you will need to connect your smart device for the mirror view.
Therefore, we don't think opening this feature is a good idea.
If no further questions, we will close this.
