### ISSUE TITLE
<AP> Comments on DOD Player on a MAC

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/APP-Software-Issue#5]
"DOD Player on a MAC is bad design" from AU customer feedback- 
  map menu in Chinese, no zoom in feature, takes too long to upload files

**Comment by dod-pm1** [comment]
Map menu is related with the server we are using, which is in Taiwan. 
Regarding the zoom in feature, teach the customer how to use it, as the video I sent you.
Close if satisfied.

**Comment by DOD-AP-Sales** [comment]
nice vid, thanks, but customer kept saying the "zoom in" function is for enlarging the vid to check out the car plate number better.

**Comment by DOD-AP-Sales** [comment]
just like what BlackVue can do.

**Comment by dod-pm1** [comment]
XD this has been answered before, nope, cannot do.
We do not wish to waste more money on this version of DOD player, due to the reason this is more of a "base function" which should be  written into the structure since the beginning.
Adding it now will NOT add great value to our products, which means the C/P value is very low.

**Comment by DOD-AP-Sales** [comment]
thanks la.
